* CL03A105MP3NSN Multilayer Ceramic Capacitor Spice Model
*-----------------------------------------------------------------------------------------------
* Model Generated by Samsung Electro-Mechanics
* Samsung Spice Model Version 5.0
* Date : Feb-10-2026
* Products : Multilayer Ceramic Capacitor(General)
*-----------------------------------------------------------------------------------------------
* Characteristics :
*
*     Nominal Capacitance = 1uF
*     Capacitance Tolerance = ¡¾20%
*     TCC = X5R(-55 ~ +85 degC.)
*     Rated Voltage = 10Vdc
*     Size = 0201(unit:inch), 0603(unit:mm)
*     Length = 0.60¡¾0.05mm
*     Width = 0.30¡¾0.05mm
*     Thickness = 0.30¡¾0.05mm
*     Reliability level = Standard
*     Lineup = Lineup Normal
*     Feature = Features Normal
*     Measurement Temperature : 25degC.
*     DC bias Value = 0V
*     Frequency : 100Hz ~ 6GHz
*-----------------------------------------------------------------------------------------------
* External Node Assignments :
*
*  1  o---||---o  2
*
*-----------------------------------------------------------------------------------------------
.SUBCKT CL03A105MP3NSN_Precise_DC0V_25degC 1 2
C1 1 3 8.23048E-7
C2 3 4 1.59270E-5
C3 4 5 7.42084E-5
C4 5 6 2.44178E-5
C5 6 7 2.38036E-5
C6 7 8 2.28088E-5
C7 8 9 2.44574E-5
C8 9 10 1.37912E-5
C16 17 18 2.20583E-5
C17 18 19 3.73338E-4
C18 19 20 1.16891E-4
C19 20 21 2.22122E-4
C20 21 22 2.53303E-4
C21 22 23 2.53303E-4
C22 23 24 2.53303E-4
C23 24 25 1.23761E-5
C24 25 26 1.96367E-6
C25 26 27 3.68290E-8
C26 27 28 1.21773E-10
C27 28 2 2.53303E-4
L10 11 12 5.62815E-11 Rser=0.0
L11 12 13 3.36497E-11 Rser=0.0
L12 13 14 3.85089E-11 Rser=0.0
L13 14 15 1.0E-10 Rser=0.0
L14 15 16 1.0E-10 Rser=0.0
L15 16 17 1.0E-10 Rser=0.0
L16 17 18 8.25068E-11 Rser=0.0
L17 18 19 1.60661E-12 Rser=0.0
L18 19 20 1.97455E-12 Rser=0.0
L19 20 21 5.76718E-13 Rser=0.0
L20 21 22 1.0E-10 Rser=0.0
L21 22 23 1.0E-10 Rser=0.0
L22 23 24 1.0E-10 Rser=0.0
L23 24 25 5.55548E-12 Rser=0.0
L24 25 26 1.93823E-11 Rser=0.0
L25 26 27 8.90154E-11 Rser=0.0
L26 27 28 4.02544E-12 Rser=0.0
L27 28 2 1.0E-10 Rser=0.0
R1 1 3 1.0E8
R2 3 4 392.85125
R3 4 5 71.26020
R4 5 6 17.52368
R5 6 7 2.54532
R6 7 8 0.38914
R7 8 9 0.05092
R8 9 10 0.01321
R9 10 11 0.00536
R11 12 13 0.05451
R12 13 14 0.36725
R13 14 15 1.0E-6
R14 15 16 1.0E-6
R15 16 17 1.0E-6
R16 17 18 7.12643E-4
R17 18 19 1.59940E-4
R18 19 20 1.58135E-4
R19 20 21 7.06561E-5
R20 21 22 1.0E-6
R21 22 23 1.0E-6
R22 23 24 1.0E-6
R23 24 25 0.00181
R24 25 26 0.00555
R25 26 27 0.01721
R26 27 28 0.53276
R27 28 2 1.0E-6
.ENDS CL03A105MP3NSN_Precise_DC0V_25degC